/* Hangman 80s Word Bank */
const WORDS = [
    'PACMAN', 'ATARI', 'NINTENDO', 'TETRIS', 'ASTEROIDS',
    'TRON', 'GALAGA', 'CENTIPEDE', 'DONKEYKONG', 'FROGGER',
    'QBERT', 'DEFENDER', 'TEMPEST', 'JOUST', 'DIGDUG',
    'ZAXXON', 'MISSILE', 'BREAKOUT', 'PONG', 'ROBOTRON',
    'SYNTHWAVE', 'DELOREAN', 'WALKMAN', 'BOOMBOX', 'ARCADE',
    'CASSETTE', 'NEON', 'RADICAL', 'TUBULAR', 'GNARLY',
    'MULLET', 'LEGWARMERS', 'RUBIKS', 'GHOSTBUSTERS', 'RAMBO'
];

export default WORDS;
